### ISSUE TITLE
Adding code

### ISSUE THREAD

**Issue by Reru01** [barbarbar338/reaction-role#9]
I am trying to add the code to existing code and it is not working. The attached txt file is the code I am trying to run and it is not working. the files I have are this one (as bot.js) and auth.json, plus the package and node_module files installed with discord and winston extensions. The first bit works just fine, but the reaction roles part does not. I don't know JS but am trying to create a custom bot. Also if you know how to make the bot make a custom message itself that would be nice, and make it so I can separate the portions of the code into different files (like a command file, a roles file, and others for the future) I guess this isn't really just help with the reaction roles I am asking for, so feel free to help minimally.
[New Text Document.txt](https://github.com/barbarbar338/reaction-role/files/4645836/New.Text.Document.txt)
I am wanting the bot to create a post similar to this image, if you don't mind helping with that too
https://imgur.com/a/pJRsiot

**Comment by barbarbar338** [comment]
First of all, I would like to welcome you!


I have reviewed the files you have added and it seems that there is not much trouble in their code. However, the system works as follows. You must first send a message to the channel (for example, an embed message as in the image you specified). 
You have to work with the ID of the message you sent and the ID of the channel. Also, the bot must see the emojis you will use. Also, I recommend you to create your bot object with reaction-role instead of directly importing the discord package.

[If you want, you can get live support by joining my Discord server!](http://router.is-my.fun/support)

**Comment by Reru01** [comment]
Could you walk me through the process for doing all this? Like I said, I don't have any experience with any of this

**Comment by barbarbar338** [comment]
As I said, you can get live help by joining the Discord server, it is quite difficult to chat here :)
Also if you can understand, I explain how to make Discord bots in Turkish on [my YouTube channel.](https://www.youtube.com/ProjectHammer)
